# Generated by Django 2.1.5 on 2019-01-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0002_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='No',
            new_name='no',
        ),
    ]
