# Generated by Django 2.1.5 on 2019-01-25 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0003_auto_20190124_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 14, 31, 46, 788148, tzinfo=utc), verbose_name='验收时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completeTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 14, 31, 46, 787150, tzinfo=utc), verbose_name='完修时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='faultDes',
            field=models.TextField(),
        ),
    ]
