# Generated by Django 2.1.5 on 2019-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0008_auto_20190125_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='repairGuy',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
