# Generated by Django 2.1.5 on 2019-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0010_auto_20190125_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
