# Generated by Django 2.1.5 on 2019-01-26 03:10

import PCfix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0011_auto_20190125_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to=PCfix.models.get_photo_path),
        ),
    ]
