# Generated by Django 2.1.5 on 2019-01-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0013_img_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='order',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='PCfix.Order'),
            preserve_default=False,
        ),
    ]
