# Generated by Django 2.1.5 on 2019-01-26 04:23

import PCfix.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0014_img_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default='', max_length=7)),
                ('image', models.ImageField(upload_to=PCfix.models.get_photo_path)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCfix.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='img',
            name='order',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
