# Generated by Django 2.1.5 on 2019-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0016_auto_20190127_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isAnnul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isReceive',
            field=models.BooleanField(default=False),
        ),
    ]
