# Generated by Django 2.1.5 on 2019-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0017_auto_20190129_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='annulUserOpenid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
