# Generated by Django 2.1.5 on 2019-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0018_order_annuluseropenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isAnnul',
            field=models.IntegerField(default=0),
        ),
    ]
