# Generated by Django 2.1.5 on 2019-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0019_auto_20190129_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isAnnul',
            field=models.IntegerField(default=1),
        ),
    ]
