# Generated by Django 2.1.5 on 2019-01-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0020_auto_20190129_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=5),
        ),
    ]
