# Generated by Django 2.1.5 on 2019-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCfix', '0022_auto_20190130_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(),
        ),
    ]
